---
- name: Configure new VM to be comfortable to use
  hosts: vms
  gather_facts: false
  become: yes
  vars:
    pipelining: true
  tasks:
    - name: User disclaimers
      debug: 
        msg: Git must be installed for a custom bash to be loaded
      
    - name: Install useful vim configurations
      copy:
        src: ./.vimrc
        dest: ~/.vimrc
         
    - name: Setup useful aliases
      copy:
        src: ./.bashrc
        dest: ~/.bashrc
        
    - name: Configure bash prompt configurations
      block: 
        - name: Download remote bash configurations
          git:
            repo: https://github.com/amirsil/pureline
            dest: /root/pureline

        - name: Activate bash configurations
          copy: 
            src: /root/pureline/configs/powerline_basic_8col.conf
            dest: /root/.pureline.conf
            remote_src: yes
      rescue:
        - debug:
            msg: Cannot fetch remote bash configurations, Git is not installed
