---
- name: Configure new VM to be comfortable to use
  hosts: vms
  gather_facts: false
  become: yes
  vars:
    pipelining: true
  tasks:
    - name: Install useful packages 
      yum:
        name:
          - git
          - zsh
          - vim
        state: present
        update_cache: no
    
    - name: Install oh-my-zsh
      shell: yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      ignore_errors: yes
    
    - name: Make zsh the default shell
      shell: chsh -s $(which zsh)

    - name: Install useful vim configurations
      copy:
        src: ./.vimrc
        dest: ~/.vimrc
         
    - name: Setup useful aliases and functions
      copy:
        src: ./.zshrc
        dest: ~/.zshrc       
